In [1]:
# imports!
from datasets import load_dataset
import pandas as pd
import os

/home/klopez/tda_vs_linguistics/mitll2/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# import BLIMP
nyu_mll_blimp = load_dataset("nyu-mll/blimp", "adjunct_island")
df_BLIMP = pd.DataFrame(nyu_mll_blimp['train'][:500])

# store
df_BLIMP.to_csv("~/tda_vs_linguistics/new_test/data2/nyu_mll_blimp2.csv", index=False)

In [ ]:
BLIMP_size = len(df_BLIMP)
print("Size is:", BLIMP_size)

df_BLIMP.head()

Size is: 500

,sentence_good,sentence_bad,field,linguistics_term,UID,simple_LM_method,one_prefix_method,two_prefix_method,lexically_identical,pair_id
0,Who should Derek hug after shocking Richard?,Who should Derek hug Richard after shocking?,syntax,island_effects,adjunct_island,True,False,False,True,0
1,What had Theresa walked through while talking ...,What had Theresa walked through that high scho...,syntax,island_effects,adjunct_island,True,False,False,True,1
2,Who will Katherine discover without hiring Erin?,Who will Katherine discover Erin without hiring?,syntax,island_effects,adjunct_island,True,False,False,True,2
3,Who has Colleen aggravated before kissing Judy?,Who has Colleen aggravated Judy before kissing?,syntax,island_effects,adjunct_island,True,False,False,True,3
4,What could a lot of cats break while finding a...,What could a lot of cats break all convertible...,syntax,island_effects,adjunct_island,True,False,False,True,4

In [ ]:
# import winograd
nyu_winograd = load_dataset("allenai/winogrande", "winogrande_xl", split="train")

def make_sentence_pairs(dataset):
    sentence = dataset["sentence"]
    word1 = dataset["option1"]
    word2 = dataset["option2"]
    answer = dataset["answer"]

    sentence1 = sentence.replace("_", word1)
    sentence2 = sentence.replace("_", word2)
    label = 1 if answer == word1 else 2
    
    return {
        "sentence1": sentence1,
        "sentence2": sentence2,
        "label": label
    }

# map function to dataset
alt_nyu_winograd = nyu_winograd.map(make_sentence_pairs)
df_winograd = pd.DataFrame(alt_nyu_winograd)[["sentence1", "sentence2", "label"]][:500]

# store
df_winograd.to_csv("~/tda_vs_linguistics/new_test/data2/nyu_winograd_wsc2.csv", index=False)

In [34]:
winograd_size = len(df_winograd)
print("Size is:", winograd_size)

df_winograd.head()

Size is: 500

,sentence1,sentence2,label
0,Ian volunteered to eat Dennis's menudo after a...,Ian volunteered to eat Dennis's menudo after a...,2
1,Ian volunteered to eat Dennis's menudo after a...,Ian volunteered to eat Dennis's menudo after a...,2
2,"He never comes to my home, but I always go to ...","He never comes to my home, but I always go to ...",2
3,"He never comes to my home, but I always go to ...","He never comes to my home, but I always go to ...",2
4,"Kyle doesn't wear leg warmers to bed, while Lo...","Kyle doesn't wear leg warmers to bed, while Lo...",2

In [ ]:
# modified from Shreya's code:
# link to test model: https://huggingface.co/datasets/nyu-mll/glue/viewer/mrpc
# load in data
nyu_mll_glue = load_dataset("glue","mrpc")

# take the training data
df_GLUE = pd.DataFrame(nyu_mll_glue['train'][:500])

# store
df_GLUE_path = os.path.expanduser("~/tda_vs_linguistics/new_test/data2/nyu_mll_glue2.csv")
df_GLUE.to_csv(df_GLUE_path, index=False)

In [19]:
GLUE_size = len(df_GLUE)
print("Size is:", GLUE_size)

df_GLUE.head()

Size is: 500

,sentence1,sentence2,label,idx
0,"Amrozi accused his brother , whom he called "" ...","Referring to him as only "" the witness "" , Amr...",1,0
1,Yucaipa owned Dominick 's before selling the c...,Yucaipa bought Dominick 's in 1995 for $ 693 m...,0,1
2,They had published an advertisement on the Int...,"On June 10 , the ship 's owners had published ...",1,2
3,"Around 0335 GMT , Tab shares were up 19 cents ...","Tab shares jumped 20 cents , or 4.6 % , to set...",0,3
4,"The stock rose $ 2.11 , or about 11 percent , ...",PG & E Corp. shares jumped $ 1.63 or 8 percent...,1,4

In [ ]:
# load in MULTI NLI
nyu_mll_multi = load_dataset("nyu-mll/multi_nli")

# take the training data
df_MULTI = pd.DataFrame(nyu_mll_multi['train'][:500])

# store
df_MULTI_path = os.path.expanduser("~/tda_vs_linguistics/new_test/data2/nyu_mll_multi2.csv")
df_MULTI.to_csv(df_MULTI_path, index=False)

In [23]:
MULTI_size = len(df_MULTI)
print("Size is:", MULTI_size)

df_MULTI.head()

Size is: 500

,promptID,pairID,premise,premise_binary_parse,premise_parse,hypothesis,hypothesis_binary_parse,hypothesis_parse,genre,label
0,31193,31193n,Conceptually cream skimming has two basic dime...,( ( Conceptually ( cream skimming ) ) ( ( has ...,(ROOT (S (NP (JJ Conceptually) (NN cream) (NN ...,Product and geography are what make cream skim...,( ( ( Product and ) geography ) ( ( are ( what...,(ROOT (S (NP (NN Product) (CC and) (NN geograp...,government,1
1,101457,101457e,you know during the season and i guess at at y...,( you ( ( know ( during ( ( ( the season ) and...,(ROOT (S (NP (PRP you)) (VP (VBP know) (PP (IN...,You lose the things to the following level if ...,( You ( ( ( ( lose ( the things ) ) ( to ( the...,(ROOT (S (NP (PRP You)) (VP (VBP lose) (NP (DT...,telephone,0
2,134793,134793e,One of our number will carry out your instruct...,( ( One ( of ( our number ) ) ) ( ( will ( ( (...,(ROOT (S (NP (NP (CD One)) (PP (IN of) (NP (PR...,A member of my team will execute your orders w...,( ( ( A member ) ( of ( my team ) ) ) ( ( will...,(ROOT (S (NP (NP (DT A) (NN member)) (PP (IN o...,fiction,0
3,37397,37397e,How do you know? All this is their information...,( ( How ( ( ( do you ) know ) ? ) ) ( ( All th...,(ROOT (S (SBARQ (WHADVP (WRB How)) (SQ (VBP do...,This information belongs to them.,( ( This information ) ( ( belongs ( to them )...,(ROOT (S (NP (DT This) (NN information)) (VP (...,fiction,0
4,50563,50563n,yeah i tell you what though if you go price so...,( yeah ( i ( ( tell you ) ( what ( ( though ( ...,(ROOT (S (VP (VB yeah) (S (NP (FW i)) (VP (VB ...,The tennis shoes have a range of prices.,( ( The ( tennis shoes ) ) ( ( have ( ( a rang...,(ROOT (S (NP (DT The) (NN tennis) (NNS shoes))...,telephone,1

In [ ]:
# load in SNLI
galileo_snli = load_dataset("galileo-ai/snli")

# take the training data
df_SNLI = pd.DataFrame(galileo_snli['train'])
df_SNLI_clean = df_SNLI.iloc[:1500:3] # remove repeats!

# store
df_SNLI_path = os.path.expanduser("~/tda_vs_linguistics/data2/galileo_snli2.csv")
df_SNLI_clean.to_csv(df_SNLI_path, index=False)

In [26]:
SNLI_size = len(df_SNLI_clean)
print("Size is:", SNLI_size)

df_SNLI_clean.head()

Size is: 500

,id,premise,hypothesis,label
0,0,A person on a horse jumps over a broken down a...,A person is training his horse for a competition.,1
3,3,Children smiling and waving at camera,They are smiling at their parents,1
6,6,A boy is jumping on skateboard in the middle o...,The boy skates down the sidewalk.,0
9,9,An older man sits with his orange juice at a s...,An older man drinks his juice as he waits for ...,1
12,12,Two blond women are hugging one another.,Some women are hugging on vacation.,1

In [ ]:
# load in SUPERGLUE
aps_superglue = load_dataset("aps/super_glue", "wsc")

# take the training data
df_SUPERGLUE = pd.DataFrame(aps_superglue['train'][:500])

# store
df_SUPERGLUE_path = os.path.expanduser("~/tda_vs_linguistics/new_test/data2/aps_superglue2.csv")
df_SUPERGLUE.to_csv(df_SUPERGLUE_path, index=False)

In [28]:
SUPERGLUE_size = len(df_SUPERGLUE)
print("Size is:", SUPERGLUE_size)

df_SUPERGLUE.head()

Size is: 500

,text,span1_index,span2_index,span1_text,span2_text,idx,label
0,"Mark told Pete many lies about himself, which ...",0,13,Mark,He,0,0
1,The mothers of Arthur and Celeste have come to...,1,25,mothers,them,1,0
2,Mark was close to Mr. Singer 's heels. He hear...,4,8,Mr. Singer,He,2,0
3,"The pony behaved well, sir, and showed no vice...",21,27,young gentleman,He,3,1
4,I poured water from the bottle into the cup un...,7,10,the cup,it,4,1